version: '3.8'

services:
  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./apps/nginx/app.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api

  ui:
    build:
      context: .
      dockerfile: apps/ui/Dockerfile
    command: npm run --workspace ui start:dev
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - node_libs:/app/node_modules
    env_file:
      - .env
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    command: npm run --workspace api start:dev
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - node_libs:/app/node_modules
      - ./tmp:/app/tmp
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  node_libs:
    driver: local
  db_data:
    driver: local
